version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: claims-postgres
    ports:
      - "5204:5432"
    environment:
      POSTGRES_DB: claims_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: claims-backend
    ports:
      - "3204:3204"
    depends_on:
      - postgres

  employee-claims:
    build:
      context: ./Employee-claims
    container_name: employee-claims
    ports:
      - "8008:80"
    depends_on:
      - backend

  hr-claims:
    build:
      context: ./HR-claims
    container_name: hr-claims
    ports:
      - "8009:80"
    depends_on:

      - backend

volumes:
  pgdata:

