version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: claims-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: claims_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1023
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: claims-backend
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  employee-claims:
    build:
      context: ./Employee-claims
    container_name: employee-claims
    ports:
      - "8005:80"
    depends_on:
      - backend

  hr-claims:
    build:
      context: ./HR-claims
    container_name: hr-claims
    ports:
      - "8006:80"
    depends_on:

      - backend

volumes:
  pgdata:

